version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: your_password
      DB_NAME: postgres
