version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    command: sh -c "pnpm run start:migrate"
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '9870:9870'
    volumes:
      - app_data:/app/mentacare/back-end/data

volumes:
  postgres_data:
  app_data:
