FROM node:18

# Set the user's home directory as an environment variable
ENV HOME_DIR=/home/$USER

# Install pnpm globally
RUN npm install -g pnpm

WORKDIR /app

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy the entire project
COPY . .

# Build the project
RUN pnpm run build

# Create the data directory and set permissions
RUN mkdir -p $HOME_DIR/app/mentacare/back-end/data && \
    chown -R $USER:$USER $HOME_DIR/app/mentacare/back-end/data

EXPOSE 9870

CMD ["pnpm", "run", "start:prod"]