version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - '9870:9870'
    env_file:
      - .env
    volumes:
      - app_data:/app/mentacare/back-end/data

volumes:
  postgres_data:
  app_data:
