FROM node:18

ENV HOME_DIR=/home/$USER

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

RUN pnpm run build

RUN mkdir -p $HOME_DIR/app/mentacare/back-end/data && \
    chown -R $USER:$USER $HOME_DIR/app/mentacare/back-end/data

EXPOSE 9870

CMD ["node", "dist/src/main.js"]